# Generated by Django 4.2.29 on 2026-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnsh_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
