# Generated by Django 4.2.29 on 2026-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnsh_map', '0002_alter_person_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
